### PR TITLE
feat: InferCreateFn

### PR DESCRIPTION
**Pull request by chillu**
DX improvement for reusing fixtures.

### CODE REVIEW

**Comment by chillu** [comment]
Here's a real world example to illustrate the need for this (keeping things somewhat DRY):

```typescript
import {
  useCreateAccount,
  useCreateOrganization,
  useCreateUser,
  useCreateUserAccount,
  usePrisma,
} from "@runn/prisma/factory"
import { InferCreateFn } from "test-fixture-factory"
import { test as anyTest, describe, expect } from "vitest"

import type { Query_Root } from "../__generated__/graphql.js"
import { graphqlRequest } from "../graphql.js"

type ResultData = {
  users: Query_Root["users"]
}

const test = anyTest.extend({
  prisma: usePrisma(),
  createOrganization: useCreateOrganization(),
  createAccount: useCreateAccount(),
  createUser: useCreateUser(),
  createUserAccount: useCreateUserAccount(),
})

const query = /* GraphQL */ `
  query test_users {
    users {
      id
      user_accounts {
        account_id
      }
    }
  }
`

type CreateFixturesDependencies = {
  createOrganization: InferCreateFn<typeof useCreateOrganization>
  createAccount: InferCreateFn<typeof useCreateAccount>
  createUser: InferCreateFn<typeof useCreateUser>
  createUserAccount: InferCreateFn<typeof useCreateUserAccount>
}

const createFixtures = async ({
  createOrganization,
  createAccount,
  createUser,
  createUserAccount,
}: CreateFixturesDependencies) => {
  const org1 = await createOrganization()
  const org1account1 = await createAccount({ organization_id: org1.id })
  const org1account2 = await createAccount({ organization_id: org1.id })
  const org1user1account1only = await createUser({
    account_id: org1account1.id,
    organization_id: org1.id,
  })
  const org1user2account1and2 = await createUser({
    account_id: org1account1.id,
    organization_id: org1.id,
  })
  await createUserAccount({
    account_id: org1account2.id,
    user_id: org1user2account1and2.id,
    organization_id: org1.id,
  })

  const org2 = await createOrganization()
  const org2account1 = await createAccount({ organization_id: org2.id })
  await createUser({
    account_id: org2account1.id,
    organization_id: org2.id,
  })

  return {
    org1,
    org1account1,
    org1account2,
    org1user1account1only,
    org1user2account1and2,
  }
}

describe("query users", () => {
  test("can only access users and their user_accounts in same organisation, within their account membership", async ({
    createOrganization,
    createAccount,
    createUser,
    createUserAccount,
  }) => {
    const { org1account1, org1user1account1only, org1user2account1and2 } =
      await createFixtures({
        createOrganization,
        createAccount,
        createUser,
        createUserAccount,
      })

    const result = await graphqlRequest<ResultData>({
      query,
      session: {
        accountId: org1user1account1only.account_id,
        userId: org1user1account1only.id, // user has access to only one account
      },
    })
    const data = result.data!.users
    expect(data).toMatchObject([
      {
        id: org1user1account1only.id,
        user_accounts: [{ account_id: org1account1.id }],
      },
      {
        id: org1user2account1and2.id,
        user_accounts: [{ account_id: org1account1.id }],
      },
    ])
  })

  test("can access users and their user_accounts in same organisation, across multiple accounts", async ({
    createOrganization,
    createAccount,
    createUser,
    createUserAccount,
  }) => {
    const {
      org1account1,
      org1account2,
      org1user1account1only,
      org1user2account1and2,
    } = await createFixtures({
      createOrganization,
      createAccount,
      createUser,
      createUserAccount,
    })

    const result = await graphqlRequest<ResultData>({
      query,
      session: {
        accountId: org1user1account1only.account_id,
        userId: org1user2account1and2.id, // user has access to multiple accounts
      },
    })
    const data = result.data!.users
    expect(data).toMatchObject([
      {
        id: org1user1account1only.id,
        user_accounts: [{ account_id: org1account1.id }],
      },
      {
        id: org1user2account1and2.id,
        user_accounts: [
          { account_id: org1account1.id },
          { account_id: org1account2.id },
        ],
      },
    ])
  })
})
```

**Comment by stayradiated** [comment]
@chillu That's clever, what do you think of this alternate tactic for typing these kind of functions?

```typescript
const test = anyTest.extend({ /* ... */ })

type TestContext = typeof test extends TestAPI<infer Context> ? Context : never

const createFixtures = async ({
  createOrganization,
  createAccount,
  createUser,
  createUserAccount
}: Pick<TestContext, 'createOrganization' | 'createAccount' | 'createUser' | 'createUserAccount'>) => { ... }
```

**Comment by stayradiated** [comment]
This helper is actually really useful, I think we should call it `FixtureValue`, as it works with any kind of Vitest fixture function

**Comment by stayradiated** [comment]
@chillu Looking closer at your example, I think using a function like that is a bit of anti-pattern. I think it would be better to be less DRY and create the dependencies in each test. 

We could refactor the `createUser` function to handle joining multiple accounts.

Your fixture creates two organizations, but only one is being tested - so we can skip manually creating the organizations manually.

A possible refactor could look like this:

```typescript
import {
  useCreateAccount,
  useOrganization,
  useCreateUser,
  useCreateUserAccount,
  usePrisma,
} from "@runn/prisma/factory"
import { InferCreateFn } from "test-fixture-factory"
import { test as anyTest, describe, expect } from "vitest"

import type { Query_Root } from "../__generated__/graphql.js"
import { graphqlRequest } from "../graphql.js"

type ResultData = {
  users: Query_Root["users"]
}

const test = anyTest.extend({
  prisma: usePrisma(),
  organization: useOrganization(),
  createAccount: useCreateAccount(),
  createUser: useCreateUser(),
  createUserAccount: useCreateUserAccount(),
})

const query = /* GraphQL */ `
  query test_users {
    users {
      id
      user_accounts {
        account_id
      }
    }
  }
`

describe("query users", () => {
  test("can only access users and their user_accounts in same organisation, within their account membership", async ({
    createAccount,
    createUser,
    createUserAccount,
  }) => {
    const accountA = await createAccount()
    const accountB = await createAccount()

    const userA = await createUser({ joinAccounts: [accountA] })
    const userB = await createUser({ joinAccounts: [accountA, accountB] })

    const result = await graphqlRequest<ResultData>({
      query,
      session: {
        accountId: org1user1account1only.account_id,
        userId: org1user1account1only.id, // user has access to only one account
      },
    })
    const data = result.data!.users
    expect(data).toMatchObject([
      {
        id: org1user1account1only.id,
        user_accounts: [{ account_id: org1account1.id }],
      },
      {
        id: org1user2account1and2.id,
        user_accounts: [{ account_id: org1account1.id }],
      },
    ])
  })

  test("can access users and their user_accounts in same organisation, across multiple accounts", async ({
    createAccount,
    createUser,
    createUserAccount,
  }) => {
    const accountA = await createAccount()
    const accountB = await createAccount()

    const userA = await createUser({ joinAccounts: [accountA] })
    const userB = await createUser({ joinAccounts: [accountA, accountB] })

    const result = await graphqlRequest<ResultData>({
      query,
      session: {
        accountId: org1user1account1only.account_id,
        userId: org1user2account1and2.id, // user has access to multiple accounts
      },
    })
    const data = result.data!.users
    expect(data).toMatchObject([
      {
        id: org1user1account1only.id,
        user_accounts: [{ account_id: org1account1.id }],
      },
      {
        id: org1user2account1and2.id,
        user_accounts: [
          { account_id: org1account1.id },
          { account_id: org1account2.id },
        ],
      },
    ])
  })
})
```

**Pull request merged**
